<a href="https://colab.research.google.com/github/hosandi20240169-dev/CO2-Streamlit-Dashboard/blob/main/Datasciencedatacleaningbook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [35]:
os.listdir('/content/drive/MyDrive/DataScienceCW')

['P_CO2 Emissions.xlsx']

In [39]:
import pandas as pd

file_path = '/content/drive/MyDrive/DataScienceCW/P_CO2 Emissions.xlsx'

df = pd.read_excel(file_path, skiprows=4)

df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Aruba,ABW,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,2660.110136,2714.756817,2939.390272,2792.344200,2699.048789,2407.690195,...,75.842198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Andorra,AND,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Africa Eastern and Southern,AFE,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,4.530298,4.612370,4.654079,4.702848,4.980167,5.236399,...,18.069306,17.892214,17.532203,11.860916,6.363359,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,AFG,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,4.470474,5.195537,7.141315,7.187699,8.349586,9.816883,...,6.364664,4.135320,4.416434,3.182961,1.787831,NaN,NaN,NaN,NaN,NaN
4,Africa Western and Central,AFW,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,0.454398,0.476414,0.483062,0.561880,0.666292,0.924014,...,9.147182,8.970882,9.307598,6.372180,3.705202,NaN,NaN,NaN,NaN,NaN

In [40]:
df.columns = df.columns.str.strip()

In [41]:
df = df.dropna(how='all')

In [42]:
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 292 entries, 0 to 291
Data columns (total 70 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    292 non-null    object
 1   Country Code    292 non-null    object
 2   Indicator Name  292 non-null    object
 3   Indicator Code  292 non-null    object
 4   nan             244 non-null    float64
 5   nan             244 non-null    float64
 6   nan             245 non-null    float64
 7   nan             245 non-null    float64
 8   nan             249 non-null    float64
 9   nan             250 non-null    float64
 10  nan             250 non-null    float64
 11  nan             250 non-null    float64
 12  nan             250 non-null    float64
 13  nan             250 non-null    float64
 14  nan             254 non-null    float64
 15  nan             254 non-null    float64
 16  nan             254 non-null    float64
 17  nan             254 non-null    float64
 18  nan             254 non-null    float64
 19  nan             254 non-null    float64
 20  nan             254 non-null    float64
 21  nan             254 non-null    float64
 22  nan             254 non-null    float64
 23  nan             254 non-null    float64
 24  nan             252 non-null    float64
 25  nan             252 non-null    float64
 26  nan             252 non-null    float64
 27  nan             252 non-null    float64
 28  nan             252 non-null    float64
 29  nan             252 non-null    float64
 30  nan             252 non-null    float64
 31  nan             252 non-null    float64
 32  nan             252 non-null    float64
 33  nan             252 non-null    float64
 34  nan             266 non-null    float64
 35  nan             267 non-null    float64
 36  nan             267 non-null    float64
 37  nan             266 non-null    float64
 38  nan             266 non-null    float64
 39  nan             267 non-null    float64
 40  nan             267 non-null    float64
 41  nan             264 non-null    float64
 42  nan             264 non-null    float64
 43  nan             263 non-null    float64
 44  nan             264 non-null    float64
 45  nan             263 non-null    float64
 46  nan             264 non-null    float64
 47  nan             265 non-null    float64
 48  nan             260 non-null    float64
 49  nan             260 non-null    float64
 50  nan             260 non-null    float64
 51  nan             260 non-null    float64
 52  nan             260 non-null    float64
 53  nan             260 non-null    float64
 54  nan             260 non-null    float64
 55  nan             260 non-null    float64
 56  nan             260 non-null    float64
 57  nan             260 non-null    float64
 58  nan             255 non-null    float64
 59  nan             254 non-null    float64
 60  nan             254 non-null    float64
 61  nan             239 non-null    float64
 62  nan             239 non-null    float64
 63  nan             239 non-null    float64
 64  nan             239 non-null    float64
 65  nan             0 non-null      float64
 66  nan             0 non-null      float64
 67  nan             0 non-null      float64
 68  nan             0 non-null      float64
 69  nan             0 non-null      float64
dtypes: float64(66), object(4)
memory usage: 159.8+ KB

In [43]:
df_long = df.melt(
    id_vars=["Country Name", "Country Code"],
    var_name="Year",
    value_name="CO2"
)

df_long.head()

,Country Name,Country Code,Year,CO2
0,Aruba,ABW,Indicator Name,CO2 emissions (metric tons per capita)
1,Andorra,AND,Indicator Name,CO2 emissions (metric tons per capita)
2,Africa Eastern and Southern,AFE,Indicator Name,CO2 emissions (metric tons per capita)
3,Afghanistan,AFG,Indicator Name,CO2 emissions (metric tons per capita)
4,Africa Western and Central,AFW,Indicator Name,CO2 emissions (metric tons per capita)

In [46]:
df_long = df_long.dropna()

In [50]:
df_long.to_csv('/content/drive/MyDrive/DataScienceCW/cleaned_co2.csv', index=False)